In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split

print("========== Day 7 - Machine Learning Basics ==========")

df = pd.read_csv("clean_student_scores.csv")

print("\nStudent Score Dataset")
display(df)

print("\nSupervised Learning")
print("Supervised Learning is a type of Machine Learning where the model learns from labeled data.")
print("In this dataset:")
print("Input (Feature): Study_Hours")
print("Output (Target): Score")

X = df[["Study_Hours"]]
y = df["Score"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)

print("\nTrain-Test Split Completed")

print("\nTraining Features")
display(X_train)

print("\nTesting Features")
display(X_test)

print("\nTraining Target")
display(y_train)

print("\nTesting Target")
display(y_test)

print("\nLinear Regression")
print("Linear Regression is a supervised Machine Learning algorithm used to predict continuous values.")
print("It finds the best-fit line between the input feature and the target value.")

print("\nDay 7 Task Completed Successfully")

========== Day 7 - Machine Learning Basics ==========

Student Score Dataset

  Student  Study_Hours   Score
0   Akhil        2.000  25.000
1     Anu        3.000  35.000
2   Rahul        5.000  55.000
3   Sneha        6.000  65.000
4   Kiran        8.000  85.000
5   Priya        9.000  92.000
6   Rohit        5.375  45.000
7   Divya        7.000  54.625

Supervised Learning
Supervised Learning is a type of Machine Learning where the model learns from labeled data.
In this dataset:
Input (Feature): Study_Hours
Output (Target): Score

Train-Test Split Completed

Training Features

   Study_Hours
0        2.000
7        7.000
2        5.000
4        8.000
3        6.000
6        5.375

Testing Features

   Study_Hours
1          3.0
5          9.0

Training Target

0    25.000
7    54.625
2    55.000
4    85.000
3    65.000
6    45.000
Name: Score, dtype: float64

Testing Target

1    35.0
5    92.0
Name: Score, dtype: float64

Linear Regression
Linear Regression is a supervised Machine Learning algorithm used to predict continuous values.
It finds the best-fit line between the input feature and the target value.

Day 7 Task Completed Successfully